global:
  scrape_interval: 3s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "alerts.yml"  #

scrape_configs:
  - job_name: "go_app"
    static_configs:
      - targets: ["backend:8080"]
